runtime: nodejs12
env: standard

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.85
  target_throughput_utilization: 0.85
  max_pending_latency: 10000ms
  max_concurrent_requests: 70
